### PR TITLE
Signin Screen UI + Forgot PW Subscreen

### PR DESCRIPTION
**Pull request by jjanicefong**
Hi all,

I've pushed my current status on the initial 'Signin Screen'. The UI portion is complete however there are certain components that still need to be implemented. 

To do:
- TouchOpacity for Signin/Signup options
- TextInput for Username/Password

SigninScreen.js has a total of 3 comps:
1. EcoHeroLogo
2. SignInEntry
3. TreeBg

Feel free to take the Logo and Bg to use. Styling may have to be adjusted through different screens.

### CODE REVIEW

**Comment by jjanicefong** [comment]
"Adding Forgot Password Subscreen + Back Bar Comp"

Hello, I've completed the UI for the subscreen of the signin page which is forgot password. The comps have been imported into signin screen for now (I've commented them out). Still trying to figure out the TreeBg position to sit on the bottom. Bottom:0 Absolute is not working. I still need to figure out font imports.

The Backbar has been made so you guys can pull that comp to use on your screens!

**Comment by j-ulienguyen** [comment]
Fixed up some conflicts with the base premaster branch

**Comment by j-ulienguyen** [comment]
You can try to reference off my MissionBoardCard comp to figure out how to do the Sign In/Up button underline

**Comment by j-ulienguyen** [comment]
I fixed more conflicts and just commented out some comps

**Pull request merged**
