### PR TITLE
WIP: Verification Pages

### PR DESCRIPTION
**Pull request by josephbondoc**
Both still need back buttons (waiting for OnBoarding screen buttons unless they are somewhere else lol)

QR Code:
- Needs verify buton
- Bottom text

4DigitCode:
- Photo of QR Code keeps going on top of all other comps (already tried elevation on all comps, didn't work please halp)

### CODE REVIEW

**Comment by j-ulienguyen** [comment]
Can you rename the comps so its like this:

For example,
- VerificationDigitSubscreen.js -> VerificationDigit()
- VerificationQRSubscreen.js -> VerificationQR()

**Comment by j-ulienguyen** [comment]
Just leave out the photo of the QR code, since realistically it won't be an image.

For the button I created a GreenButton.js comp in which you can specify the title, width, and height.

**Comment by j-ulienguyen** [comment]
I also don't know why I am having constant issues with both of your branches as I keep getting an error.

"The development server returned response error code: 500"

Please double check your paths, comp names, etc.

**Comment by j-ulienguyen** [comment]
What's the progress on this

**Comment by josephbondoc** [comment]
WIP: Green Button, confirmation-code comp

Trying to get the confirmation code to work but having trouble understanding the syntax needed 

**Refer to this documentation for the confirmation code**
https://www.npmjs.com/package/react-native-confirmation-code-field

Currently having problems getting the Green Button to show up below where the confirmation code is, only shows on the page if not put in any <View> containers

**Comment by j-ulienguyen** [comment]
Can you pull from premaster to get latest changes? And also fix up the conflicts

**Pull request merged**
